name: CI

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://koalaman/shellcheck-alpine
        with:
          args: /bin/sh -c "shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh"
  ici:
    env:
      TRACE: true
      CLANG_TIDY_ARGS: -quiet -export-fixes ${{ github.workspace }}/.work/clang-tidy-fixes.yml
      BASEDIR: ${{ github.workspace }}/.work
    strategy:
      fail-fast: false
      matrix:
        include:
          # Tidy
          - {ROS_DISTRO: noetic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: true}
          - {ROS_DISTRO: melodic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: pedantic, EXPECT_EXIT_CODE: 1}
          - {ROS_DISTRO: melodic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: pedantic, CLANG_TIDY_ARGS: "-checks=-*,modernize-use-nullptr", EXPECT_EXIT_CODE: 1}


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './'
        with:
          config: ${{toJSON(matrix)}}
      - name: Adapt ${{ env.BASEDIR }}/clang-tidy-fixes.yml
        run: |
          ls -al ${{ env.BASEDIR }}
          cat ${{ env.BASEDIR }}/clang-tidy-fixes.yml && sudo sed -i "s#/.work/target_ws/src/#/industrial_ci/mockups/#g" ${{ env.BASEDIR }}/clang-tidy-fixes.yml || true
      - name: Process clang-tidy results
        if: always() && matrix.CLANG_TIDY && github.event_name == 'pull_request'
        uses: platisd/clang-tidy-pr-comments@master
        with:
          # The GitHub token (or a personal access token)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the clang-tidy fixes generated previously
          clang_tidy_fixes: ${{ env.BASEDIR }}/clang-tidy-fixes.yml
          # Request changes in case warnings are found
          request_changes: true
          # Set the number of comments per review to avoid GitHub API timeouts for heavily loaded PRs
          suggestions_per_comment: 10
