name: CI

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://koalaman/shellcheck-alpine
        with:
          args: /bin/sh -c "shellcheck -x *.sh industrial_ci/scripts/*_ci industrial_ci/src/*.sh industrial_ci/src/*/*.sh"
  ici:
    env:
      TRACE: true
      CLANG_TIDY_ARGS: -quiet -export-fixes ${{ github.workspace }}/.work/clang-tidy-fixes.yml
      BASEDIR: ${{ github.workspace }}/.work
    strategy:
      fail-fast: false
      matrix:
        include:
          # Tidy
          - {ROS_DISTRO: noetic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: true}
          - {ROS_DISTRO: melodic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: pedantic, EXPECT_EXIT_CODE: 1}
          - {ROS_DISTRO: melodic, TARGET_WORKSPACE: 'industrial_ci/mockups/test_clang_tidy', CLANG_TIDY: pedantic, CLANG_TIDY_ARGS: "-checks=-*,modernize-use-nullptr", EXPECT_EXIT_CODE: 1}


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './'
        with:
          config: ${{toJSON(matrix)}}
      - name: Process clang-tidy warnings
        if: always() && matrix.CLANG_TIDY
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: ${{ env.BASEDIR }}/clang-tidy-fixes.yml
